Iter15
ilya372317/must-have-metrics pull request #16
Opened 2023-12-22 03:37 UTC by ilya372317

Ветка называется iter14, что бы тесты запостились. На ней есть код для iter15

2023-12-24 15:56 UTC, maxlyaptsev requested changes

2023-12-24 15:56 UTC, maxlyaptsev commented on internal/client/sender/sender.go
> +	}
можно сделать клиентскую мидлвару и возвращать такой модифицированный http-клиент - который будет внутри сам добавлять подпись. Так не будет путаницы и никакой запрос случайно не отправится без подписи. Пример:

```go
NewSender(client SenderClient) *sender {
    return &sender{
        client: client // модифицированный клиент 
    }
}
```

Вот пример как сделать мидвалру https://github.com/go-resty/resty?tab=readme-ov-file#request-and-response-middleware

2023-12-24 15:56 UTC, maxlyaptsev commented on internal/client/statistic/monitor.go
> +	for k := 0; k < int(rateLimit); k++ {
rate limit это другое - это ограничение количества запросов в момент времени. Даже если по задумке эти значения совпадают, другой разработчик скажет что тут ошибка прочитав имя переменной
```suggestion
	for k := 0; k < int(poolSize); k++ {
```

2023-12-24 15:56 UTC, maxlyaptsev commented on internal/client/statistic/monitor.go
> +		go func() {
NIT: если возникнет паника в одной горутине то все приложение остановится. Но можно в каждой горутине ловить эту панику (правда все равно понадобится перезапуск) и выводить например ошибку, не останавливая приложения

2023-12-24 15:56 UTC, maxlyaptsev commented on internal/handlers/helpers.go
> +}
Кажется я уже видел такой код в sender.go) 
Напрашивается вынос в отдельный пакет

2023-12-24 15:56 UTC, maxlyaptsev commented on internal/handlers/helpers.go
> +package handlers
не рекомендуется использовать имя helper - очень размытое называние.
Но и переименовать тоже мало. Почему тут не использовать middleware, которые изучили не так давно?

2023-12-26 03:38 UTC, ilya372317 commented on internal/client/statistic/monitor.go
> +	for k := 0; k < int(rateLimit); k++ {
++

2023-12-26 03:38 UTC, ilya372317 commented on internal/handlers/helpers.go
> +}
++

2023-12-26 04:13 UTC, ilya372317 commented on internal/handlers/helpers.go
> +package handlers
++

2023-12-26 05:51 UTC, ilya372317 commented on internal/client/sender/sender.go
> +	}
Для этого придется сжатие перенести тоже в middleware, на сколько я понимаю. Смущает что и для сжатия и для подписи, придется читать request.Body оба раза и восстанавливать его как то так:
`request.Body = io.NopCloser(bytes.NewReader(body))`
Или есть другой способ? Вообще на сколько нормальная идея, восстанавливать body? для (1-1)

2023-12-26 06:16 UTC, ilya372317 commented on internal/client/statistic/monitor.go
> +		go func() {
Добавил отлов паник в рабочем пуле, но хотелось бы на 1-1 по подробнее это обсудить, есть опасение что может возникнуть цикл бесконечных паник, и по сути приложение так и так не будет рабоать (для 1-1)

2023-12-26 06:16 UTC, ilya372317 commented on internal/client/statistic/monitor.go
> +		go func() {
++

2023-12-28 09:55 UTC, ilya372317 commented on internal/client/sender/sender.go
> +	}
++

2023-12-30 07:19 UTC, merged