Iter18
ilya372317/must-have-metrics pull request #18
Opened 2024-02-26 03:20 UTC by ilya372317

2024-02-28 20:23 UTC, maxlyaptsev requested changes

2024-02-28 20:23 UTC, maxlyaptsev commented on internal/client/statistic/monitor_test.go
> +func BenchmarkMonitor_collectStat1(b *testing.B) {
запустил твой бенчмарк и посмотрел результаты. Алокаций показалось много
<img width="954" alt="image" src="https://github.com/ilya372317/must-have-metrics/assets/10906726/f0cecace-804d-4077-91e6-7bc1ecc84cc2">

Сделал несколько итераций и исследований, пришел вот к такому результату.  Не буду оставлять спойлеров - попробуй сам оптимизировать используя этот бенч

<img width="976" alt="image" src="https://github.com/ilya372317/must-have-metrics/assets/10906726/eeacc73e-466b-42f8-8956-5a9e781a86f3">

2024-03-01 03:27 UTC, ilya372317 commented on internal/client/statistic/monitor_test.go
> +func BenchmarkMonitor_collectStat1(b *testing.B) {
++

<img width="1022" alt="Снимок экрана 2024-03-01 в 10 26 51" src="https://github.com/ilya372317/must-have-metrics/assets/46264563/0e40a438-b2af-439c-86b2-77208b3cb1db">

2024-03-01 04:35 UTC, ilya372317 commented on internal/client/statistic/monitor_test.go
> +func BenchmarkMonitor_collectStat1(b *testing.B) {
Так же нагрузил сервис с помощью vegeta, результаты и конфигурацию сохранил в папке {project_root}/vegeta
<img width="1105" alt="Снимок экрана 2024-03-01 в 11 33 09" src="https://github.com/ilya372317/must-have-metrics/assets/46264563/ed7d2295-a03f-4b55-b46a-86bf5290e9cd">
Больше всего времени занимает ожидание ответа от базы данных, при 300 RPS максимальное время ответа не превышала 80ms

2024-03-08 15:28 UTC, merged