Iter5
ilya372317/must-have-metrics pull request #5
Opened 2023-11-03 12:42 UTC by ilya372317

2023-11-05 19:15 UTC, maxlyaptsev requested changes

2023-11-05 19:15 UTC, maxlyaptsev commented on internal/client/sender/reportSender.go
> +	defer res.Body.Close()
defer обычно ставят сразу после кода который нужно закрыть. В конце можно уже без defer но удобство именно в том что закрытие рядом и этот код не теряется

2023-11-05 19:15 UTC, maxlyaptsev commented on internal/client/statistic/monitor.go
> +func MakeMonitor() Monitor {
```suggestion
func NewMonitor() Monitor {
```
Конструкторы принято начинать с New, при этом можно и заканчивать, если других конструкторов в пакете нет

2023-11-05 19:15 UTC, maxlyaptsev commented on cmd/server/main.go
> +	host = flag.String("a", "localhost:8080", "server address")
```suggestion
	host = flag.String("a", DEFAULT_SERVER_ADDR, "server address")
```
было бы удобней вынести в константу

2023-11-05 19:15 UTC, maxlyaptsev commented on cmd/server/main.go
> +		log.Fatalf("vailed to start server on port 8080: %v", err)
```suggestion
		log.Fatalf("vailed to start server on port ?: %v", err)
```
во флаге может быть другое значение

2023-11-05 19:15 UTC, maxlyaptsev commented on internal/client/sender/reportSender.go
> +package sender
по поводу названий файлов и этого в частности  - в go принято использовать только строчные буквы, без тире и нижних подчеркиваний. Часто из-за этого ограничения приходится много разных названий перебирать, целое искусство, но что поделаешь). _test - исключение
В данном случае лучше использовать просто sender.go или reporter.go

2023-11-05 19:15 UTC, maxlyaptsev commented on internal/errors/error.go
> +type AlertNotFound struct{}
в целом было бы достаточно объявить ошибку как 
```go
var alertNotFound  errors.New("alert not found in storage")
//...
return nil, alertNotFound
```
либо в нужном месте возвращать  ее :
```go
return nil, errors.New("alert not found in storage")
```
Т.е. обычно нет нет смысла заводить как отдельный тип. Если объявлена как переменная - мы можем сравнить с помощью `errors.Is` (https://pkg.go.dev/errors#example-Is) и проблем не возникает

Т.е. тут немного отличается концепция от исключений. Ошибки в go используются постоянно везде и каждую заводить отдельным типом - оверхед. Но в целом ничего против не имею.

2023-11-05 19:15 UTC, maxlyaptsev commented on internal/storage/storage.go
> +type AlertStorage interface {
Интерфейс объявляем только там где используем. И максимально неподробный. Т.е. если нам нужен только один метод - описываем только его. Так большее количество реализаций смогут удовлетворить этому интерфейсу. 

Можно почитать подробней почему так, даже отдельные доклады этому посвящают. Связано с тем что в go не имплементируются интерфейсы, они существуют сами по себе. И любая структура сможет его удовлетворить.

Например, у нас есть ручка которая сохраняет метрику. Мы описываем интерфейс Saver в котором есть метод Save(). Теперь любой Storage который имеет такой метод может быть использован в качестве аргумента

2023-11-07 03:32 UTC, ilya372317 commented on internal/client/sender/reportSender.go
> +	defer res.Body.Close()
++

2023-11-07 03:33 UTC, ilya372317 commented on internal/client/statistic/monitor.go
> +func MakeMonitor() Monitor {
++

2023-11-07 03:33 UTC, ilya372317 commented on cmd/server/main.go
> +	host = flag.String("a", "localhost:8080", "server address")
++

2023-11-07 03:33 UTC, ilya372317 commented on cmd/server/main.go
> +		log.Fatalf("vailed to start server on port 8080: %v", err)
++

2023-11-07 03:33 UTC, ilya372317 commented on internal/client/sender/reportSender.go
> +package sender
++

2023-11-07 03:33 UTC, ilya372317 commented on internal/errors/error.go
> +type AlertNotFound struct{}
++

2023-11-07 03:33 UTC, ilya372317 commented on internal/storage/storage.go
> +type AlertStorage interface {
++

2023-11-08 17:00 UTC, maxlyaptsev commented on internal/client/sender/reportSender.go
> +	defer res.Body.Close()
ну лучше было бы все же вариант в defer оставить, просто поднять повыше)

2023-11-08 17:03 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	Records map[string]entity.Alert
```suggestion
	records map[string]entity.Alert
```

Не стоит давать сюда публичный доступ

2023-11-08 17:05 UTC, maxlyaptsev approved these changes

2023-11-09 02:50 UTC, merged