Iter9
ilya372317/must-have-metrics pull request #9
Opened 2023-11-24 14:39 UTC by ilya372317

2023-11-28 16:44 UTC, maxlyaptsev requested changes

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/utils/logger/logger.go
> +func createStorageIfNotExists() {
как это в логере оказалось?

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/utils/compress/compress.go
> +type Writer struct {
а почему это не в мидлваре? Кусок там, кусок здесь. Зачем делить на два разных пакета?

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/utils/basepath.go
> +	return filepath.Join(filepath.Dir(b), "../..")
читаю по файлам - "утилита для базового пути" - ничего не понятно. А внутри одна строка. Кажется не целесообразно из-за двух строк создавать целый пакет

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/server/middleware/filemetrics.go
> +func SaveMetricsInFile(repo FilesystemSupportStorage) Middleware {
Это не мидлвара. Мидлвары срабатывают в момент до обработки запроса и содержит логику которая связана с запросом:
- залогировать запрос
- распаковать если он сжат
- записать метрику
- записать трейс
- сделать авторизацию (разрешить/запретить доступ)

А сохранение в файл очень ресурсоемкая операция. По тексту задания файл нужно сохранять асинхронно и периодически, не замедляя запрос

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/server/entity/alert.go
> +	Value interface{}
лучше создать две разные структуры - интерфейсы это крайний вариант, уходим от строгой типизации

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/server/entity/alert.go
> +	}
я не понял что тут написано если честно. Создается структура которая в себя кладет родительску? Зачем?

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/config/params/parameter.go
> +}
в этом коде вообще никакого смысла нет. Парсим конфигурацию складываем в структуру, которая отображает те же поля что могут быть переданы во флагах или в переменных окружения

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/config/params/host.go
> +}
зачем фнукция для этого? Можно же просто константу вписать или вообще строкой. Не дает ничего - такой же хардкод только более сложный и упакованный в функцию

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/dto/metricdto.go
> +	body, err := io.ReadAll(r.Body)
лишняя переменная, анмаршалить нужно сразу io.Reader

2023-11-28 16:44 UTC, maxlyaptsev commented on internal/dto/validator/validator.go
> +func Validate(dataTransferObject interface{}) (bool, error) {
валидатор чего? Зачем  он в отельном пакете, что он валидирует?

2023-11-29 02:41 UTC, ilya372317 commented on internal/utils/logger/logger.go
> +func createStorageIfNotExists() {
Эта функция создает папку где будет лежать файл лога, выбрал не удачный нейминг, поправил

2023-11-29 02:45 UTC, ilya372317 commented on internal/server/entity/alert.go
> +	}
Взял из примера уроков практикума, создаю новую структуру, что бы избежать рекурсии при json.Unmarshal(). Но после того как сделаю у Alert поле Value не интерфейсным типом, я удалю этот код

2023-11-29 03:26 UTC, ilya372317 commented on internal/dto/validator/validator.go
> +func Validate(dataTransferObject interface{}) (bool, error) {
Он валидирует в моем случае объекты DTO, а вынес в отдельный пакет так как кастомные валидации которые в нем регистрируются смогут быть в одном месте. Лучше вынести в пакет где он используется? И еще если он понадобится в других пакетах, стоит ли в этом случае создавать отдельный пакет, или переопределять в каждом отдельно? (вопрос записал для 1 - 1)

2023-11-29 03:26 UTC, ilya372317 commented on internal/dto/metricdto.go
> +	body, err := io.ReadAll(r.Body)
++

2023-11-29 03:29 UTC, ilya372317 commented on internal/config/params/parameter.go
> +}
С помощью этого кода я хотел абстрагироваться от логики получения переменных окружения и флагов, когда для нас самым важным является переменная окружения а потом флаг. Если понадобится добавить новый флаг + переменную окружения, достаточно будет определить еще одну структуру и зарегистрировать ее. Как можно сделать лучше?  (для 1 - 1)

2023-11-29 05:44 UTC, ilya372317 commented on internal/utils/basepath.go
> +	return filepath.Join(filepath.Dir(b), "../..")
пакет utils уже был же, а то что он в отдельном файле, так лучше не делать? Вообще решил вынести эту функцию в пакет utils потому что на нужна мне в 2 других пакетах (handler, logger) и придется ее завуалировать там, если не выносить. + логика функции зависит от ее места расположения, и копирую ее в места использования, придется думать на каком она расстоянии от базовой папки проекта. Как сделать лучше? (для 1 - 1)

2023-11-29 05:48 UTC, ilya372317 commented on internal/server/middleware/filemetrics.go
> +func SaveMetricsInFile(repo FilesystemSupportStorage) Middleware {
По тексту задания, если значение 0, то нужно сохранять синхронно. Не понимаю где лучше разместить этот код? (для 1 - 1)

2023-11-29 05:49 UTC, ilya372317 commented on internal/utils/compress/compress.go
> +type Writer struct {
++

2023-11-30 04:29 UTC, ilyaotinov commented on internal/server/entity/alert.go
> +	Value interface{}
++

2023-11-30 04:31 UTC, ilya372317 commented on internal/utils/logger/logger.go
> +func createStorageIfNotExists() {
++

2023-11-30 09:03 UTC, ilya372317 commented on internal/dto/validator/validator.go
> +func Validate(dataTransferObject interface{}) (bool, error) {
Решили на 1-1 что можно оставить

2023-12-01 03:47 UTC, ilya372317 commented on internal/config/params/host.go
> +}
++

2023-12-01 03:47 UTC, ilya372317 commented on internal/config/params/parameter.go
> +}
++

2023-12-01 03:48 UTC, ilyaotinov commented on internal/server/entity/alert.go
> +	}
++

2023-12-01 05:13 UTC, ilya372317 commented on internal/utils/basepath.go
> +	return filepath.Join(filepath.Dir(b), "../..")
Относительный путь не работает тестах, так как точка входа меняется. Не придумал как сделать без этой функции и что бы работало одинаково на всех окружениях и в тестах

2023-12-01 06:04 UTC, ilyaotinov commented on internal/server/middleware/filemetrics.go
> +func SaveMetricsInFile(repo FilesystemSupportStorage) Middleware {
++

2023-12-01 17:14 UTC, maxlyaptsev commented on internal/utils/basepath.go
> +	return filepath.Join(filepath.Dir(b), "../..")
посмотрел, у нас же абсолютный путь всегда передается - и по умолчанию он /tmp/metrics-db.json
в тестах тоже можем туда писать, но выбрать другое имя например для проверки

2023-12-02 04:27 UTC, ilya372317 commented on internal/utils/basepath.go
> +	return filepath.Join(filepath.Dir(b), "../..")
Записал в вопросы для 1-1 на следующий спринт. Согласен на счет файла логов и пути для сохранения метрик, но не очень ясно как быть с html template, ведь он часть нашей кодовой базы и до него абсолютный путь не указать

2023-12-02 04:27 UTC, merged